# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='用户部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='DetailWorkContents',
            fields=[
                ('did', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='详细的工作内容')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Identify_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户公司姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='用户公司邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='JobHandover',
            fields=[
                ('jid', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_contents', models.TextField(verbose_name='交接工作内容')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='用户角色名称')),
            ],
        ),
        migrations.CreateModel(
            name='SubResponse',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('subtitle', models.CharField(max_length=32, unique=True, verbose_name='子url')),
                ('avatar', models.ImageField(default='avatar/1.jpg', upload_to='avatar/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='用户部门')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Role', verbose_name='用户角色')),
            ],
        ),
        migrations.CreateModel(
            name='WeekReports',
            fields=[
                ('wid', models.BigAutoField(primary_key=True, serialize=False)),
                ('weekly_content', models.TextField(verbose_name='周报内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('main_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkContents',
            fields=[
                ('wid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('status', models.BooleanField(default=False, verbose_name='工作是否办结')),
                ('main_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='主要负责人')),
            ],
        ),
        migrations.AddField(
            model_name='subresponse',
            name='sub_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subperson', to='app01.UserInfo', verbose_name='次要负责人id'),
        ),
        migrations.AddField(
            model_name='subresponse',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app01.WorkContents', verbose_name='工作内容id'),
        ),
        migrations.AddField(
            model_name='jobhandover',
            name='hand_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='现工作负责人'),
        ),
        migrations.AddField(
            model_name='jobhandover',
            name='original_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='app01.UserInfo', verbose_name='原工作负责人'),
        ),
        migrations.AddField(
            model_name='detailworkcontents',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.WorkContents', verbose_name='工作id'),
        ),
    ]
